[wip] [7 of #107] expand env parsing and command creation
conda-incubator/setup-miniconda pull request #127
Opened 2020-12-21 14:42 UTC by bollwyvl

This collapses the boolean logic for parsing an environment file, and adds the parsed environment (as yaml or explicit lines) to the dynamic options. Subsequently, it moves the "create an env" logic to dedicated files for "simple" conda create, create with a lockfile and `env update` with a YAML. This drops a _lot_ from `setup.ts`, and notably a number of transient dependencies (`yaml`, etc).

- continues #107
- includes
  - #126  
- might help #122?

## On the next PR

> refactor the tools provider

Apply a similar treatment as this PR to the provisioning of tools in the base env (e.g. `mamba`, `conda-build`), prior to installation of the environment.

Again, we need a way to say, _hey, my base env already/only has `mamba`_. One Does Not Simply Parse a Conda MatchSpec, though... so I guess I'd rather it was explicit, e.g. `installer-has-mamba`, which we'd be able to pre-populate for `mambaForge` rather than trying to do anything with `mamba-version`.

2020-12-21 15:01 UTC, bollwyvl commented
Diff's getting a little nasty, will keep this `wip` until #126 lands...

2020-12-22 20:50 UTC, goanpeca commented
#126 landed @bollwyvl

2020-12-23 02:43 UTC, bollwyvl commented on src/types.ts
> + * A strategy for ensure an environment is up-to-date vs the action inputs
typo, will batch with other review fixes

2020-12-23 16:15 UTC, bollwyvl commented on src/conda.ts
> +    .split(/[,\n]/)
this inadvertently allows for `\n` in addition to `,` as a channel separator. having both is probably a bug unless we document it... will revert to existing behavior.

the correct behavior is probably to _only_ use `\n` _if_ there is a (non-trailing?) `\n` in the value

2020-12-23 16:25 UTC, goanpeca commented on src/conda.ts
> +    .split(/[,\n]/)
Sounds good. The correct behavior to me would be to have all commas or all line separators.

Could we do something like `/(,)|(\n)/`and count each group?

2020-12-24 01:42 UTC, goanpeca commented on src/conda.ts
> +    process.env["GITHUB_WORKSPACE"] || "",
Should we use the home path?

2020-12-24 01:43 UTC, goanpeca commented on src/conda.ts
> +  // all other options
Feel like all these comments should be capitalized, unless there is some sort of TS convention.

2020-12-24 01:43 UTC, goanpeca commented on src/constants.ts
> + * TODO: this should be generalized, and, along with roundtrip parsing/generating
Yeah, could be :)

2020-12-24 01:47 UTC, goanpeca commented on src/utils.ts
> + * create a conda veersion spec string.
Typo

2020-12-24 01:47 UTC, goanpeca requested changes
Couple of questions, and also I feel like all comments should be capitalized 🤷🏽

2020-12-24 03:36 UTC, bollwyvl commented on src/conda.ts
> +    process.env["GITHUB_WORKSPACE"] || "",
I think we need to assume sourcing the config from the workspace, which may or may not be in home.

the `CONDARC_PATH` on the other hand _is_ in `HOME`, as reported by `os.homedir()`

2020-12-24 03:44 UTC, bollwyvl commented on src/conda.ts
> +    .split(/[,\n]/)
As i said, let's not monkey with the newlines on this PR, will put it back to comma-only.

If, for some awful reason, someone _must_ have a `,` in their URL, as it _is_ part of the RFC, allowing both is going to break, hard. 

Typographically, just commas scans quickly horizontally, while the lines look more like all the other conda docs. I don't see a huge win to supporting both in one, either:
```yaml
channels: |
  conda-forge,defaults
  https://www.crazy.town/conda-remote/
```
one must really parse what each line is saying, and there's no whitespace to help...

2020-12-24 03:47 UTC, goanpeca commented on src/conda.ts
> +    .split(/[,\n]/)
Ok, commas for now then :)

2020-12-24 16:07 UTC, bollwyvl commented
Hopefully all typos/capitalization handled on
https://github.com/conda-incubator/setup-miniconda/pull/127/commits/64e43746f1144df89ec0c932169bfaec527fe6b3

2020-12-24 16:09 UTC, goanpeca approved these changes

2020-12-24 16:09 UTC, merged