Fix condaBasePath when useBundled is false, and there's no pre-existing conda
conda-incubator/setup-miniconda pull request #299
Opened 2023-11-06 22:18 UTC by isuruf

Useful when using setup-miniconda with self-hosted runners without conda installed.

2023-11-14 21:26 UTC, goanpeca requested changes
@isuruf why did you remove the code for the mac case? 

It seems like this change will break something. Could you confirm 🤔 ?

2023-11-14 21:31 UTC, isuruf commented
It's the same as `path.join(os.homedir(), "miniconda3");` right?

2023-11-14 21:35 UTC, goanpeca commented
>It's the same as path.join(os.homedir(), "miniconda3"); right?

I think not, and home dir might have been pointing somewhere else on mac, hence the hardcoded path. Could you please verify?

2023-11-14 22:46 UTC, isuruf commented
With `macos-latest` image it is the home directory.

2023-11-21 14:44 UTC, isuruf commented
Ping on this

2023-11-21 15:00 UTC, dbast commented
How about running:
```
conda create -n github-action nodejs=16 -c conda-forge
conda activate github-action
npm ci
npm run build
```

and committing the resulting updates so that the example runs actually test the changes proposed by this PR?

2023-11-26 19:23 UTC, goanpeca approved these changes

2023-11-26 19:23 UTC, goanpeca approved these changes

2023-11-26 19:25 UTC, merged

2023-11-26 19:27 UTC, isuruf commented
Thanks @goanpeca