add an option for install directory of mini{forge,conda}
conda-incubator/setup-miniconda pull request #342
Opened 2024-04-11 20:13 UTC by isuruf

This is useful for self-hosted runners where we can change the installation directory to the workspace directory to allow automatic cleaning up of the miniforge/miniconda environments.

2024-04-15 18:22 UTC, isuruf commented
cc @finnagin

2024-04-22 21:10 UTC, jaimergp reviewed
Just one comment about the name chosen for now. Implementation looks ok. We should add an example test to make sure this works as intended.

2024-04-22 21:10 UTC, jaimergp commented on action.yml
> +  install-dir:
I'm inclined to using `installation-directory` here instead. The rest of the options in this project seem to be using no abbreviations (e.g. we fully spell `environment` instead of `env`).

2024-04-23 02:29 UTC, goanpeca commented on action.yml
> +  install-dir:
Hi @isuruf, indeed I agree with @jaimergp comment, we should try to use full names :)

2024-04-23 02:30 UTC, goanpeca requested changes, later dismissed
Thanks for working on this @isuruf 

Could we add information on this usage on the README?

Also could we add some sort of workflow to test this?

If this only makes sense for self hosted runners, maybe we could add something on this PR https://github.com/conda-incubator/setup-miniconda/pull/301 ?

2024-10-30 19:43 UTC, jaimergp approved these changes

2024-10-30 19:43 UTC, merged

2024-10-30 19:43 UTC, jaimergp commented
Thanks!