Remove defaults channel on input `channel: nodefaults`
conda-incubator/setup-miniconda pull request #364
Opened 2024-08-26 22:44 UTC by liamhuber

Changes conda setup to run `conda config --remove channels defaults` when `nodefaults` is found in the `channels` input instead of adding the `- nodefaults` channel. I.e.

```
- uses: conda-incubator/setup-miniconda
      with:
        channels: conda-forge,nodefaults
        channel-priority: strict
```

Will correctly give

```
channels:
- conda-forge
dependencies:
...
```

Instead of 

```
channels:
- conda-forge
- nodefaults
dependencies:
...
```

[Here is a log](https://github.com/liamhuber/test-setup-minconda/actions/runs/10568363909/job/29279169033) of the modified version in action.

Closes #207

2024-08-27 21:42 UTC, liamhuber commented
The failure of 6 is by design:

```
 CondaKeyError: 'channels': 'defaults' is not in the 'channels' key of the config file
  
  
  
  CondaKeyError: 'channels': 'defaults' is not in the 'channels' key of the config file
  
Error: The process '/home/runner/miniconda3/condabin/conda' failed with exit code 1
```

2024-08-27 21:58 UTC, liamhuber commented
Example 6 during `Adding tools to 'base' env...`:

```
  Removing channel defaults
  /home/runner/miniconda3/condabin/conda config --remove channels defaults
  Warning: 
  CondaKeyError: 'channels': 'defaults' is not in the 'channels' key of the config file
  
  
  
  CondaKeyError: 'channels': 'defaults' is not in the 'channels' key of the config file
```

The patch is working as-intendend and in `Applying initial configuration...` we correctly get:

```
  Removing channel defaults
  /home/runner/miniconda3/condabin/conda config --remove channels defaults
```

But then there's something in the Ex6 config that differs from [my simple test case](https://github.com/liamhuber/test-setup-minconda/blob/main/.github/workflows/nodefaults-patch.yml) that causes it to double-dip for `defaults`.

2024-08-27 22:05 UTC, liamhuber commented
Ok, got it: the setup [runs `applyCondaConfiguration`](https://github.com/conda-incubator/setup-miniconda/blob/e5293c8fd23bf30f6ad37a6281c8a924c8938440/src/base-tools/index.ts#L62) a _second_ time. So it's just my own new if-clause come to bite me.

2024-08-27 23:32 UTC, liamhuber commented
Ok, the log shows the `nodefaults` option correctly purging the `defaults` channel. After that, `defaults` gets added back in because it's included explicitly in `etc/example-environment.yml`. This is a bit odd when `nodefaults` gets passed to as an action arg, but it is internally consistent with the existing behaviour where the provided env file is the highest authority, so it seems reasonable to me. I'm content with this and feel this is ready for review.

2024-09-08 04:41 UTC, liamhuber commented
@conda-incubator/setup-miniconda tests are passing, just waiting on a review.

2024-09-10 09:49 UTC, jaimergp commented on dist/setup/index.js
> +            if (channel === "nodefaults") {
```suggestion
            if (channel === "nodefaults") {
                core.info("Removing channel defaults");
```

2024-09-10 09:50 UTC, jaimergp commented on src/conda.ts
> +    if (channel === "nodefaults") {
```suggestion
    if (channel === "nodefaults") {
      core.info("Removing channel defaults");
```

2024-09-10 09:51 UTC, jaimergp reviewed
Just a tiny comment with the logging statements. LGTM otherwise.

2024-09-10 11:22 UTC, jezdez commented
I don't agree we should further the "nodefaults" workaround in setup-miniconda, it's a bad API since it's not an actual channel and tends to increase the risk of a messy channel management

2024-09-10 11:53 UTC, jezdez commented
I think it might be enough to simply offer "override_channels" as a config option, which requires specifying a channel but doesn't hard-code the "nodefaults" workaround.

2024-09-10 11:57 UTC, jezdez requested changes
A more explicit and future-proof solution is relying on the `--override-channels` CLI option since `nodefaults` is a pretty bad workaround within conda. That way, running `conda config --remove channels defaults` isn't needed here.

2024-09-10 16:04 UTC, liamhuber commented
> Just a tiny comment with the logging statements. LGTM otherwise.

@jaimergp, nice catch! Committed 🚀 

> I don't agree we should further the "nodefaults" workaround in setup-miniconda, it's a bad API since it's not an actual channel and tends to increase the risk of a messy channel management...

@jezdez, the current situation is one "bad" API and a second API that _silently_ deviates from the first API in an unproductive way (i.e. a channel named "nodefaults" is literally added to the channels list). Regardless of whether the `conda` API is good or bad, I would strongly recommend `conda-incubator/setup-miniconda` favour consistency over goodness where the two APIs use the same terminology. 

I definitely like your suggested `--override-channels` solution, but I see it as a "yes, and" approach, and I'm afraid you'll need to identify a different volunteer for its implementation.

2024-09-10 16:07 UTC, liamhuber commented
Nice, even better, if https://github.com/conda/conda/pull/14227 is merged I think we can even simply close this PR?

2024-09-10 18:08 UTC, jaimergp commented
Yep, timing will work this time. The only other workaround right now is to explicitly pass a `condarc` file correctly populated to the `condarc-file` input.

2024-09-10 18:19 UTC, liamhuber commented
> Yep, timing will work this time. The only other workaround right now is to explicitly pass a `condarc` file correctly populated to the `condarc-file` input.

Haha, yep, did exactly that downstream a couple weeks ago! https://github.com/pyiron/actions/pull/129

2024-09-27 04:08 UTC, oursland commented
Builds are breaking in CI as the package `defaults/noarch::conda-libmamba-solver-23.12.0` is being selected, which is incompatible.

2024-09-27 16:15 UTC, liamhuber commented
@oursland I'm afraid I don't have enough context to understand your statement. The only thing breaking here was the linter test -- which failed because I never rebuilt the committed ts suggestions into the js.

I did that now, but I also see that https://github.com/conda/conda/pull/14227 got merged last week. @jaimergp my understanding is that now we just need to wait for the next release of conda, and this PR becomes completely unnecessary, yeah? If that's the case I think we can just close this PR.

2024-09-27 16:32 UTC, oursland commented
GitHub Actions should not be considered like a normal software release as this is a piece of core CI infrastructure and is not something that can always be deferred until the next release of an upstream package, which will then be packaged into a release, and eventually distribution.

The current behavior of `setup-miniconda` still breaks GitHub actions.  During update, it pulls in an incompatible version of `libmamba-solver` from the `defaults` channel.  This has been breaking CI for FreeCAD among others.

2024-09-27 16:53 UTC, liamhuber commented
> GitHub Actions should not be considered like a normal software release as this is a piece of core CI infrastructure and is not something that can always be deferred until the next release of an upstream package, which will then be packaged into a release, and eventually distribution.

I don't think I feel as strongly about it, but I also don't disagree. My opinion doesn't matter though, I'm just a rando who patched what was bothering me. If you want to get this in ASAP you'll need to convince the two reviewers.

If you want something immediately that avoids erroneously including the defaults, you can check out https://github.com/pyiron/actions/blob/main/cached-miniforge/action.yml, a wrapper for `setup-miniconda` that patches over the defaults issue and solves an edge case in caching (https://github.com/conda-incubator/setup-miniconda/issues/361)

> The current behavior of `setup-miniconda` still breaks GitHub actions. During update, it pulls in an incompatible version of `libmamba-solver` from the `defaults` channel. This has been breaking CI for FreeCAD among others.

I'm afraid I'm a little lost again. Do you mean the main branch of `setup-miniconda`, or do you mean that you tried out this branch and something I've done here broke the `libmamba-solver` versioning? If it's the main branch, raising a separate issue and referencing this PR might be the way to go; if it's something I've done here I'll need some assistance tracking down the problem -- at least a MWE for the breakage -- as I don't usually do any work in javascript.

2024-09-27 17:35 UTC, oursland commented
> I'm afraid I'm a little lost again. Do you mean the main branch of setup-miniconda, or do you mean that you tried out this branch and something I've done here broke the libmamba-solver versioning?

The main branch is broken.  This PR fixes the issue.  Waiting what could be months for to fix CI is not a reasonable strategy.

Your fix through caching is unfortunately not feasible for our application.  For FreeCAD and others, we already use 100% of our GitHub provided caching storage budget for various compiler caches.

2024-09-27 18:19 UTC, liamhuber commented
@oursland, the action I linked also removes the `defaults` channel; if this PR fixes your problem, it's likely that action will provide immediate relief as well -- the caching issue is an additional, unrelated issue it fixes. It is not a pure-wrapper though -- it will also try to pip install your local package by default -- but you should have enough flexibility in the inputs to get it to work as a pure wrapper. If you need something to solve the `defaults` problem _immediately_, I recommend trying that.

2024-09-27 20:04 UTC, jakirkham commented
AIUI Conda will go through a depreciation cycle before removal. It will probably be a bit before installers come prebaked with the newer Conda

Not to mention some users may pin an installer version as part of this workflow

Given this, think this change still is desirable. What do we need to do to get it in?

2024-09-28 10:50 UTC, jaimergp commented
Thanks @jakirkham, yes, when I posted this comment I had gone for the straight removal disregarding the deprecation cycle, which was brought in the code review.

This change is still needed as a result, but I think @jezdez doesn't want the `nodefaults` hack in more places, so we'll have to come up with a different solution.

My ideas:

- Warn about `channels` implicitly adding `defaults`
- Add a new setting to remove `defaults` if not in `channels` explicitly. Something like `ignore_defaults_in_channels`.

Since this is a new approach, I'll open a new PR. Thanks all for the fruitful discussion!

2024-09-28 17:20 UTC, oursland commented
> Add a new setting to remove defaults if not in channels explicitly. Something like ignore_defaults_in_channels.

This is the expected behavior.  If I provide a list of channels, then I expect that those channels and only those channels are being used.  The inclusion of `defaults` implicitly in the channels list was a surprise when it caused breakage in our builds.  I consider this inclusion to be a bug.

I personally do not believe an additional flag to remove `defaults` should be necessary as I consider it's implicit inclusion to be a bug that should be resolved.

2024-09-30 10:50 UTC, jaimergp commented
Believe it or not, it was intentionally designed that way. Not an oversight. You are "adding" channels to the list, which is prepopulated with `defaults`. I agree it is not great UX, so that's why `conda` is deprecating that using the standard deprecation window of three months.

If anything, the bug is here in setup-miniconda because we are using `conda config --add` to populate the channels, and it wasn't clear in the documentation that it happened that way. The option would have been better called `add_channels`. Since we can't guarantee that changing the default will break users workflows, the conservative way forward is adding a flag that people can opt-in to, and eventually turn it on by default. If you'd like to advocate for a more aggressive change, [let's discuss that in the new PR.](https://github.com/conda-incubator/setup-miniconda/pull/367)

2024-09-30 17:59 UTC, jakirkham commented
Yep that is reasonable Jaime. Am not saying it needs to be this fix, but we do need something

How about we do the same thing we do in conda-forge? Namely `conda config --remove channels defaults`, which gives us

```
# .condarc
channels: []
```

Then we can add any channels after

2024-09-30 18:25 UTC, liamhuber commented
Regardless of whether the `nodefaults` syntax is good or not, and even in the presence of the new better PR, I would actually still suggest also merging this PR. As long as conda itself supports `nodefaults` in the channels removing defaults, I feel it would be wise to synchronize behaviour in the channels arg here. Literally adding `nodefaults` to the channels list is unexpected and undesirable.

2024-09-30 18:53 UTC, jakirkham reviewed
Thanks Liam! 🙏

Perhaps a concrete suggestion makes it clearer what I'm proposing. Please let me know what you think 🙂

2024-09-30 18:53 UTC, jakirkham commented on dist/setup/index.js
>          for (const channel of channels.slice().reverse()) {
```suggestion
        if (channels.length) {
            yield condaCommand(["config", "--remove", "channels", "defaults"], options);
        }
        for (const channel of channels.slice().reverse()) {
```

2024-09-30 18:53 UTC, jakirkham commented on dist/setup/index.js
> +            }
```suggestion
            core.info(`Adding channel '${channel}'`);
            yield condaCommand(["config", "--add", "channels", channel], options);
```

2024-09-30 18:53 UTC, jakirkham commented on src/conda.ts
>    for (const channel of channels.slice().reverse()) {
```suggestion
if (channels.length) {
    yield condaCommand(["config", "--remove", "channels", "defaults"], options);
}
for (const channel of channels.slice().reverse()) {
```

2024-09-30 18:53 UTC, jakirkham commented on src/conda.ts
> +    }
```suggestion
    core.info(`Adding channel '${channel}'`);
    yield condaCommand(["config", "--add", "channels", channel], options);
```

2024-09-30 20:16 UTC, liamhuber commented on dist/setup/index.js
>          for (const channel of channels.slice().reverse()) {
Doesn't this change the behaviour so that the absence of `defaults` is the new default behaviour?

I actually disagree with @oursland that including `defaults` by default is a bug that needs to be removed -- at least here. I'm 100% in favour of getting rid of it in the default behaviour of `conda` itself, but for me it's important that `setup-miniconda` be _consistent_ with `conda` where they share terminology (like "channels"). To this end I actually don't recommend changing the default behaviour, and still never want to see the channel `nodefaults` explicitly get added to the channels list.

Ie fix problems upstream, and keep behaviour downstream consistent with upstream (maybe adding extra convenience on top of that consistency as in... can't find the link on mobile, but you know, the other PR relevant here)

2024-09-30 20:44 UTC, jakirkham commented on dist/setup/index.js
>          for (const channel of channels.slice().reverse()) {
In the case when a user specifies `channels` (like below), it would only use those `channels`

https://github.com/conda-incubator/setup-miniconda/blob/8f65dda9671afc08d384e37681333ed70e2d5306/README.md?plain=1#L349-L353

If no `channels` are specified, it would fallback to the default behavior of the selected installer/Conda (typically using `defaults`)

2024-09-30 20:46 UTC, liamhuber commented on dist/setup/index.js
>          for (const channel of channels.slice().reverse()) {
But this still differs from default `conda` behviour, yeah? Where `defaults` is included by default and setting the channel `nodefaults` removes it rather than adding a channel `nodefaults`?

2024-09-30 20:55 UTC, jakirkham commented on dist/setup/index.js
>          for (const channel of channels.slice().reverse()) {
Not sure I follow

We don't specify how the `channel` public API of this GHA is implemented. It could be specified through `conda config` commands (like now) or it could be specified by writing out a `condarc` or it could be options tacked onto each `conda create`/`conda install` command or some other way not currently being considered

Think relying on how these public APIs are implemented under-the-hood is relying on an implementation detail, which would be subject to change. There is no guarantee the implementation details would remain the same

2024-09-30 20:56 UTC, liamhuber commented
It's maybe worth quickly revisiting why this PR exists: I ran into the nasty situation that `defaults` was getting added to my channels even if I didn't ask for it, #186. When I looked at `conda`, I saw this could be fixed by adding the channel `nodefaults`, but in `setup-miniconda` this simply literally added the channel `nodefaults`!

Now the real solution is to fix this upstream in `conda`, which is exactly what @jaimergp did https://github.com/conda/conda/pull/14227, so to the extend that this PR raised the visibility of #186 high enough to motivate that change, it's a full success. Everything after that real, upstream fix to the fundamental problem is just transient window dressing.

But what window dressing should there be? IMO, unless it is very explicitly documented, `setup-miniconda` should behave like `conda` where we would naively expect it to. That means I don't recommend getting rid of `defaults` by default; extending _new_ syntax to get rid of `defaults` like in #367 is great; and where `setup-miniconda` input looks like `conda` input and behaves _almost_ like conda input, it ought to behave _exactly_ like conda input -- anything else is just super confusing.

I patched the problem downstream in my own workflows by initializing an empty `.condarc`, so I've got basically zero skin in this game beyond trying to be a helpful neighbour. My feelings won't be hurt if you close this and just run with #367 until https://github.com/conda/conda/pull/14227 eventually becomes the `conda` standard -- but for the sake of other users, it's my earnest recommendation to drive for consistency between `setup-conda` and `conda` above other considerations.

2024-09-30 20:58 UTC, jakirkham commented on dist/setup/index.js
>          for (const channel of channels.slice().reverse()) {
Though did miss we do say we will add `defaults` to the end of the list 🤦‍♂️ 

https://github.com/conda-incubator/setup-miniconda/blob/8f65dda9671afc08d384e37681333ed70e2d5306/README.md?plain=1#L335-L337

That said, I think this is worth breaking. It would mean using a major version bump

2024-10-03 20:41 UTC, jakirkham commented
If we are going to add this with a warning, should we instead tailor the warning to...

1. Warn users that don't have defaults explicitly listed (and are getting it automatically), that they will need to in the next Miniforge major release
2. Include this fix and warn that `nodefaults` will become standard behavior and the option will go away in the next release

Just thinking fewer deprecation cycles and more targeted at the end result that we want

2024-10-04 00:31 UTC, liamhuber commented
That sounds wise. Feel free to make a suggestion in the ts with the message worded how you want it, and I'm happy to commit it and rebuild the js

2024-10-30 18:33 UTC, jaimergp commented
Closes by #367

2024-10-30 18:33 UTC, closed without merging